### PR TITLE
Make pylint happy

### PR DESCRIPTION
**Pull request by koszti**
# Description of change

Pylint is currently failing because new checks introduced in the latest version

This PR fixes pylint warnings and pin pylint to latest.

### CODE REVIEW

**Review by Samira-El — APPROVED** [review]

**Comment by amofakhar** [comment]
LGTM, just a comment:
I think it's better to use same standard for defining strings, if it is decided to use single quotation, follow it in all the codes.

**Comment by koszti** [comment]
> LGTM, just a comment: I think it's better to use same standard for defining strings. if it is decided to use single quotation, follow it in all the codes.

Fair, where is the script that’s checking quotes vs double quotes in the repos? I can't find them

**Comment by koszti** [comment]
> LGTM, just a comment: I think it's better to use same standard for defining strings. if it is decided to use single quotation, follow it in all the codes.

PR updated and made the change as you requested. I also added `pylintrc` and a new code formatter check to the CI.

**Review by amofakhar — APPROVED** [review]
LGTM

**Pull request merged**
